name: Coverage

on:
    push:
        branches: [main]
        paths:
            - ".github/workflows/coverage.yml"
            - "src/**"
            - "include/**"
            - "tests/**"
            - "build.zig"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    coverage:
        permissions:
            contents: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: actions/cache@v4
              with:
                  path: /home/linuxbrew/.linuxbrew
                  key: brew-${{ runner.os }}

            - uses: mlugg/setup-zig@v2
              with:
                  version: 0.15.2

            - name: Install kcov
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential curl git libdw-dev

                  if [ ! -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
                      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                  fi

                  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

                  echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
                  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

                  brew update
                  brew install kcov

            - name: Run coverage report generator
              run: |
                  zig build cov
                  mv zig-out/coverage .

            - name: Commit coverage report & badge
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  if git show-ref --quiet refs/heads/coverage; then
                      git checkout coverage
                  else
                      git checkout --orphan coverage
                      git reset --hard
                  fi

                  mv coverage/* .

                  git add .
                  git commit -m "Update coverage report"
                  git push -f origin coverage
