name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/coverage.yml'
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - '.github/CMakeLists.txt'

jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja lcov llvm llvm-dev

      - name: Run coverage report generator
        run: |
          cd .github && mkdir build && cd build
          CC=clang CXX=clang++ cmake -G Ninja ..
          cmake --build .
          cd .. && mv build/coverage ../coverage

      - name: Commit coverage report & badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan coverage || git checkout coverage
          git reset --hard
          cp -r coverage/coverage_report/* .
          cp coverage/coverage_summary.txt .
          cp coverage/coverage.svg .
          rm -rf build
          git add .
          git commit -m "Update coverage report"
          git push -f origin coverage
